// Created by iWeb 2.0.4 local-build-20090908

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,66),url:'Inspect_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Inspect_files/stroke_17.png'},{rect:new IWRect(1,-1,182,2),url:'Inspect_files/stroke_18.png'},{rect:new IWRect(183,-1,2,2),url:'Inspect_files/stroke_19.png'},{rect:new IWRect(183,1,2,66),url:'Inspect_files/stroke_20.png'},{rect:new IWRect(183,67,2,2),url:'Inspect_files/stroke_21.png'},{rect:new IWRect(1,67,182,2),url:'Inspect_files/stroke_22.png'},{rect:new IWRect(-1,67,2,2),url:'Inspect_files/stroke_23.png'}],new IWSize(184,68)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,45),url:'Inspect_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Inspect_files/stroke_25.png'},{rect:new IWRect(1,-1,182,2),url:'Inspect_files/stroke_26.png'},{rect:new IWRect(183,-1,2,2),url:'Inspect_files/stroke_27.png'},{rect:new IWRect(183,1,2,45),url:'Inspect_files/stroke_28.png'},{rect:new IWRect(183,46,2,2),url:'Inspect_files/stroke_29.png'},{rect:new IWRect(1,46,182,2),url:'Inspect_files/stroke_30.png'},{rect:new IWRect(-1,46,2,2),url:'Inspect_files/stroke_31.png'}],new IWSize(184,47)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,-1,1,394),url:'Inspect_files/stroke.png'},{rect:new IWRect(-2,-2,1,1),url:'Inspect_files/stroke_1.png'},{rect:new IWRect(-1,-2,417,1),url:'Inspect_files/stroke_2.png'},{rect:new IWRect(416,-2,1,1),url:'Inspect_files/stroke_3.png'},{rect:new IWRect(416,-1,1,394),url:'Inspect_files/stroke_4.png'},{rect:new IWRect(416,393,1,1),url:'Inspect_files/stroke_5.png'},{rect:new IWRect(-1,393,417,1),url:'Inspect_files/stroke_6.png'},{rect:new IWRect(-2,393,1,1),url:'Inspect_files/stroke_7.png'}],new IWSize(415,392)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,93),url:'Inspect_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Inspect_files/stroke_9.png'},{rect:new IWRect(1,-1,182,2),url:'Inspect_files/stroke_10.png'},{rect:new IWRect(183,-1,2,2),url:'Inspect_files/stroke_11.png'},{rect:new IWRect(183,1,2,93),url:'Inspect_files/stroke_12.png'},{rect:new IWRect(183,94,2,2),url:'Inspect_files/stroke_13.png'},{rect:new IWRect(1,94,182,2),url:'Inspect_files/stroke_14.png'},{rect:new IWRect(-1,94,2,2),url:'Inspect_files/stroke_15.png'}],new IWSize(184,95))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Inspect_files/InspectMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
